ignoreErrors = ["error-missing-instagram-accesstoken"]
baseURL = "https://marycreazioni.ml"
disqusShortname = "marycreazioni"
languageCode = "it-it"
languageName = "It"
paginate = "5"
theme = "marycreazioni"
title = "MaryCreazioni"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "about"
weight = 2
# [[menu.main]]
# name = "Category"
# url = "categories/nature/"
# weight = 3
[[menu.main]]
name = "Contact"
url = "contact"
weight = 4
# [[menu.main]]
# name = "Privacy Policy"
# url = "privacy-policy"
# weight = 5
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Dario Caricchio"
contact_form_action = "#"
copyright = "Designed & Developed By [Dario Caricchio](https://dariocaricchio.ml/)"
description = "This is meta description"
logo = "images/mary_creazioni_cropped.gif"
search = false # true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "css/instafeed.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = "images/mary_creazioni_cropped.gif"
